version: "3.7"

services:
  # app:
  #   # The app service definition
  mysql:
    platform: linux/x86_64
    # user:root
    image: mysql:5.7
    volumes:
      - running-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_DATABASE: "running-db"
    ports:
      - "4000:3306"

volumes:
  running-mysql-data:
